services:
  - type: web
    name: lakeshorepower-crm-api
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
